### ISSUE TITLE
Project Portfolio Page

### ISSUE THREAD

**Issue by kcubey** [AY1920S2-CS2113-T15-2/tp#122]
- Create the first version of your Project Portfolio Page (PPP).
  - Reason: Each member needs to create a PPP to describe your contribution to the project.

https://nus-cs2113-ay1920s2.github.io/website/schedule/week12/project.html#2-draft-the-ppp

**Comment by alexlim510** [comment]
Add portfolio page (Alex)

**Comment by kcubey** [comment]
All members have added their PPP. Closing issue
