### ISSUE TITLE
View cards

### ISSUE THREAD

**Issue by kcubey** [AY1920S2-CS2113-T15-2/tp#136]
![image](https://user-images.githubusercontent.com/15946120/78974371-6aeb0080-7b44-11ea-883e-65c7a09ac707.png)

Are we allowing the viewer to see the Q & A when running listcard?

**Comment by Jeremy733** [comment]
Probably just the questions are better

**Comment by JeremyTakigawa** [comment]
When listing is fine, as long as answers don't appear immediately in quiz I reckon

**Comment by kcubey** [comment]
Hmm but then how can the viewer see the card? Do we have a function for that? @JeremiasLiew @alexlim510

**Comment by kcubey** [comment]
for v2.1, since the purpose of the flashcard program is to quiz yourself we have implemented it such that the user is unable to see the answer when listing cards. They are only able to see the answers when they quiz themselves. 

To be possible implementation for v3 onwards, closing issue
