### ISSUE TITLE
Error message loops itself

### ISSUE THREAD

**Issue by JeremyTakigawa** [AY1920S2-CS2113-T15-2/tp#37]
If load file was removed by hand, the error message loops indefinitely

**Comment by kcubey** [comment]
When is the file removed? Is it after opening the app then remove the file?

**Comment by JeremyTakigawa** [comment]
> When is the file removed? Is it after opening the app then remove the fi

**Comment by JeremyTakigawa** [comment]
> When is the file removed? Is it after opening the app then remove the file?

Run the programme and then remove the file. I think it's something todo with the try block looping itself. Should be fine since users should not have access to the txt file.
