### ISSUE TITLE
As a student I want to be able to determine my scores for each subject

### ISSUE THREAD

**Issue by alexlim510** [AY1920S2-CS2113-T15-2/tp#41]
I can focus on weaker subjects.

Jeremias - ScoreList, show quiz result upon quiz completion
Kezia - To update storage based on new structure, update quiz commands (Parser)

User Stories: 8
Import from #21

**Comment by JeremiasLiew** [comment]
To resolve ScoreList issue

**Comment by kcubey** [comment]
>  Kezia - quiz command parser
update quiz command (Parser)

**Comment by kcubey** [comment]
Updated storage in #115
