### ISSUE TITLE
Tut/Project Requirements Wk10: Update DG with design details, UG update

### ISSUE THREAD

**Issue by kcubey** [AY1920S2-CS2113-T15-2/tp#56]
https://nus-cs2113-ay1920s2.github.io/website/schedule/week10/project.html
Update the Developer Guide file in the repo as follows:
* Each member should describe the implementation of at least one enhancement she has added (or planning to add).
  Expected length: 1+ page per person
* The description can contain things such as,
  * How the feature is implemented (or is going to be implemented).
  * Why it is implemented that way.
  * Alternatives considered.
* Diagramming tools: You may use any tool (e.g., PowerPoint) to draw UML diagrams. If you do, choose a tool that allows incremental updates to diagrams (reason: because diagrams need to be updated multiple times as the product evolves). For example, if you use PowerPoint to draw diagrams, also commit the source PowerPoint files so that they can be reused when updating diagrams in future.
* If you want to use PowerPoint to draw UML diagrams, you can use the 'UML Reference Sheet' pptx file in LumiNUS as a template (it has all the basic shapes you need). After drawing the diagram in a slide using PowerPoint shapes, select the entire diagram, right-click, and choose Save as picture.

**Comment by alexlim510** [comment]
Sequence diagrams:
1. Command
2. Add Card
3. Delete Subject
4. Score
5. Quiz
6. Listcard (optional)
7. Storage

**Comment by kcubey** [comment]
UG help/command reformatting & update
