### ISSUE TITLE
Update Events - UG, Help commands (UI)

### ISSUE THREAD

**Issue by kcubey** [AY1920S2-CS2113-T15-2/tp#75]
Error messages to verify

"showupcoming d/NUMBER OF DAYS" - lists events from 'today' till 'today' + NUMBEROFDAYS in chronological order

"listevents" - lists all events in the order the exam has been added

addevent e/[EVENTTOPIC] d/[DATE] - Eventtopic is just a String,
Date is any of:
dd-MM-yyyy
dd/MM/yyyy
dd.MM.yyyy
dd-MMM-yyyy
Accepts things like 3/5/20 also

**Comment by JeremiasLiew** [comment]
Update UG for Events
